# Generated by Django 4.2.2 on 2023-08-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagne', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagne',
            options={'ordering': ['-Date_Ajout']},
        ),
    ]
