# Generated by Django 4.2.2 on 2023-08-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagne', '0003_pagne_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagne',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
