# Generated by Django 4.2.2 on 2023-08-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagne', '0004_pagne_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
